services:
  server:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: go_server
    env_file:
      - ./.env
    ports:
      - "8080:8080" # Serveur accessible sur le port 8080
    networks:
      - go_api_mongo_scrapper_network
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - ./.env
    ports:
      - "27017:27017" # Exposer MongoDB sur le port 27017
    volumes:
      - db_data:/data/db
    networks:
      - go_api_mongo_scrapper_network

volumes:
  db_data:

networks:
  go_api_mongo_scrapper_network:
